### ISSUE TITLE
libv8 fails to build on macOS 10.15 (Catalina, darwin19)

### ISSUE THREAD

**Issue by lloeki** [rubyjs/libv8#280]
Clean install of macOS Public Beta 19A501i, Xcode 11 beta 2 11M337n. No Homebrew, just system Ruby (2.6.3-p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19])

Tried multiple versions of the gem (from 6.7.288.46.1 to 7.3.492.27.3beta1), same failure: Seems like the call to `gclient sync` fails.

No binary version published yet, so it obviously falls back to building. Log output below.

if you don't have access to a darwin19 machine, I can try things provided I'm given directions.

```
current directory: /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/ext/libv8
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20190708-4194-1brvt9g.rb extconf.rb
creating Makefile
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor/_gclient_v8_zsjbYI' in '/Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor'
Cloning into '/Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor/_gclient_v8_zsjbYI'...
remote: Sending approximately 850.11 MiB ...        
remote: Counting objects: 1           
remote: Counting objects: 5501           
remote: Counting objects: 7754, done        
remote: Finding sources:   1% (1/94)           
remote: Finding sources:   2% (2/94)           
remote: Finding sources:   3% (3/94)           
remote: Finding sources:   4% (4/94)           
remote: Finding sources:   5% (5/94)           
remote: Finding sources:   6% (6/94)           
remote: Finding sources:   7% (7/94)           
remote: Finding sources:   8% (8/94)           
remote: Finding sources:   9% (9/94)           
remote: Finding sources:  10% (10/94)           
remote: Finding sources:  11% (11/94)           
remote: Finding sources:  12% (12/94)           
remote: Finding sources:  13% (13/94)           
remote: Finding sources:  14% (14/94)           
remote: Finding sources:  15% (15/94)           
remote: Finding sources:  17% (16/94)           
remote: Finding sources:  18% (17/94)           
remote: Finding sources:  19% (18/94)           
remote: Finding sources:  20% (19/94)           
remote: Finding sources:  21% (20/94)           
remote: Finding sources:  22% (21/94)           
remote: Finding sources:  23% (22/94)           
remote: Finding sources:  24% (23/94)           
remote: Finding sources:  25% (24/94)           
remote: Finding sources:  26% (25/94)           
remote: Finding sources:  27% (26/94)           
remote: Finding sources:  28% (27/94)           
remote: Finding sources:  29% (28/94)           
remote: Finding sources:  30% (29/94)           
remote: Finding sources:  31% (30/94)           
remote: Finding sources:  32% (31/94)           
remote: Finding sources:  34% (32/94)           
remote: Finding sources:  35% (33/94)           
remote: Finding sources:  36% (34/94)           
remote: Finding sources:  37% (35/94)           
remote: Finding sources:  38% (36/94)           
remote: Finding sources:  39% (37/94)           
remote: Finding sources:  40% (38/94)           
remote: Finding sources:  41% (39/94)           
remote: Finding sources:  42% (40/94)           
remote: Finding sources:  43% (41/94)           
remote: Finding sources:  44% (42/94)           
remote: Finding sources:  45% (43/94)           
remote: Finding sources:  46% (44/94)           
remote: Finding sources:  47% (45/94)           
remote: Finding sources:  48% (46/94)           
remote: Finding sources:  50% (47/94)           
remote: Finding sources:  51% (48/94)           
remote: Finding sources:  52% (49/94)           
remote: Finding sources:  53% (50/94)           
remote: Finding sources:  54% (51/94)           
remote: Finding sources:  55% (52/94)           
remote: Finding sources:  56% (53/94)           
remote: Finding sources:  57% (54/94)           
remote: Finding sources:  58% (55/94)           
remote: Finding sources:  59% (56/94)           
remote: Finding sources:  60% (57/94)           
remote: Finding sources:  61% (58/94)           
remote: Finding sources:  62% (59/94)           
remote: Finding sources:  63% (60/94)           
remote: Finding sources:  64% (61/94)           
remote: Finding sources:  65% (62/94)           
remote: Finding sources:  67% (63/94)           
remote: Finding sources:  68% (64/94)           
remote: Finding sources:  69% (65/94)           
remote: Finding sources:  70% (66/94)           
remote: Finding sources:  71% (67/94)           
remote: Finding sources:  72% (68/94)           
remote: Finding sources:  73% (69/94)           
remote: Finding sources:  74% (70/94)           
remote: Finding sources:  75% (71/94)           
remote: Finding sources:  76% (72/94)           
remote: Finding sources:  77% (73/94)           
remote: Finding sources:  78% (74/94)           
remote: Finding sources:  79% (75/94)           
remote: Finding sources:  80% (76/94)           
remote: Finding sources:  81% (77/94)           
remote: Finding sources:  82% (78/94)           
remote: Finding sources:  84% (79/94)           
remote: Finding sources:  85% (80/94)           
remote: Finding sources:  86% (81/94)           
remote: Finding sources:  87% (82/94)           
remote: Finding sources:  88% (83/94)           
remote: Finding sources:  89% (84/94)           
remote: Finding sources:  90% (85/94)           
remote: Finding sources:  91% (86/94)           
remote: Finding sources:  92% (87/94)           
remote: Finding sources:  93% (88/94)           
remote: Finding sources:  94% (89/94)           
remote: Finding sources:  95% (90/94)           
remote: Finding sources:  96% (91/94)           
remote: Finding sources:  97% (92/94)           
remote: Finding sources:  98% (93/94)           
remote: Finding sources: 100% (94/94)           
remote: Finding sources: 100% (94/94)        
Receiving objects:   0% (1/685986)   
Receiving objects:   1% (6860/685986)   
Receiving objects:   2% (13720/685986)   
Receiving objects:   3% (20580/685986)   
Receiving objects:   4% (27440/685986), 10.35 MiB | 20.74 MiB/s   
Receiving objects:   5% (34300/685986), 10.35 MiB | 20.74 MiB/s   
Receiving objects:   6% (41160/685986), 10.35 MiB | 20.74 MiB/s   
Receiving objects:   7% (48020/685986), 10.35 MiB | 20.74 MiB/s   
Receiving objects:   8% (54879/685986), 10.35 MiB | 20.74 MiB/s   
Receiving objects:   9% (61739/685986), 10.35 MiB | 20.74 MiB/s   
Receiving objects:   9% (65828/685986), 26.75 MiB | 26.77 MiB/s   
Receiving objects:  10% (68599/685986), 26.75 MiB | 26.77 MiB/s   
Receiving objects:  11% (75459/685986), 26.75 MiB | 26.77 MiB/s   
Receiving objects:  12% (82319/685986), 26.75 MiB | 26.77 MiB/s   
Receiving objects:  13% (89179/685986), 26.75 MiB | 26.77 MiB/s   
Receiving objects:  14% (96039/685986), 26.75 MiB | 26.77 MiB/s   
Receiving objects:  15% (102898/685986), 47.61 MiB | 31.76 MiB/s   
Receiving objects:  16% (109758/685986), 47.61 MiB | 31.76 MiB/s   
Receiving objects:  17% (116618/685986), 47.61 MiB | 31.76 MiB/s   
Receiving objects:  18% (123478/685986), 47.61 MiB | 31.76 MiB/s   
Receiving objects:  19% (130338/685986), 47.61 MiB | 31.76 MiB/s   
Receiving objects:  19% (134801/685986), 47.61 MiB | 31.76 MiB/s   
Receiving objects:  20% (137198/685986), 69.36 MiB | 34.69 MiB/s   
Receiving objects:  21% (144058/685986), 69.36 MiB | 34.69 MiB/s   
Receiving objects:  22% (150917/685986), 69.36 MiB | 34.69 MiB/s   
Receiving objects:  23% (157777/685986), 69.36 MiB | 34.69 MiB/s   
Receiving objects:  24% (164637/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  25% (171497/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  26% (178357/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  27% (185217/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  28% (192077/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  29% (198936/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  30% (205796/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  31% (212656/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  31% (215151/685986), 89.48 MiB | 35.80 MiB/s   
Receiving objects:  32% (219516/685986), 111.59 MiB | 37.21 MiB/s   
Receiving objects:  33% (226376/685986), 111.59 MiB | 37.21 MiB/s   
Receiving objects:  34% (233236/685986), 111.59 MiB | 37.21 MiB/s   
Receiving objects:  35% (240096/685986), 111.59 MiB | 37.21 MiB/s   
Receiving objects:  36% (246955/685986), 111.59 MiB | 37.21 MiB/s   
Receiving objects:  37% (253815/685986), 111.59 MiB | 37.21 MiB/s   
Receiving objects:  38% (260675/685986), 111.59 MiB | 37.21 MiB/s   
Receiving objects:  39% (267535/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  40% (274395/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  41% (281255/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  42% (288115/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  43% (294974/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  44% (301834/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  45% (308694/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  46% (315554/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  47% (322414/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  48% (329274/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  49% (336134/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  50% (342993/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  50% (344748/685986), 133.09 MiB | 38.03 MiB/s   
Receiving objects:  51% (349853/685986), 145.52 MiB | 36.39 MiB/s   
Receiving objects:  52% (356713/685986), 145.52 MiB | 36.39 MiB/s   
Receiving objects:  53% (363573/685986), 145.52 MiB | 36.39 MiB/s   
Receiving objects:  54% (370433/685986), 145.52 MiB | 36.39 MiB/s   
Receiving objects:  55% (377293/685986), 167.26 MiB | 37.17 MiB/s   
Receiving objects:  56% (384153/685986), 167.26 MiB | 37.17 MiB/s   
Receiving objects:  56% (389194/685986), 167.26 MiB | 37.17 MiB/s   
Receiving objects:  57% (391013/685986), 189.63 MiB | 39.84 MiB/s   
Receiving objects:  58% (397872/685986), 211.75 MiB | 41.11 MiB/s   
Receiving objects:  59% (404732/685986), 211.75 MiB | 41.11 MiB/s   
Receiving objects:  59% (404843/685986), 211.75 MiB | 41.11 MiB/s   
Receiving objects:  60% (411592/685986), 233.80 MiB | 41.37 MiB/s   
Receiving objects:  61% (418452/685986), 255.92 MiB | 41.46 MiB/s   
Receiving objects:  61% (418712/685986), 255.92 MiB | 41.46 MiB/s   
Receiving objects:  62% (425312/685986), 299.99 MiB | 41.87 MiB/s   
Receiving objects:  62% (430353/685986), 299.99 MiB | 41.87 MiB/s   
Receiving objects:  63% (432172/685986), 322.07 MiB | 42.00 MiB/s   
Receiving objects:  64% (439032/685986), 344.16 MiB | 44.14 MiB/s   
Receiving objects:  64% (440851/685986), 344.16 MiB | 44.14 MiB/s   
Receiving objects:  65% (445891/685986), 387.38 MiB | 43.94 MiB/s   
Receiving objects:  65% (451659/685986), 387.38 MiB | 43.94 MiB/s   
Receiving objects:  66% (452751/685986), 409.42 MiB | 43.93 MiB/s   
Receiving objects:  67% (459611/685986), 431.51 MiB | 43.93 MiB/s   
Receiving objects:  67% (464203/685986), 431.51 MiB | 43.93 MiB/s   
Receiving objects:  68% (466471/685986), 453.43 MiB | 43.89 MiB/s   
Receiving objects:  68% (472466/685986), 475.37 MiB | 43.88 MiB/s   
Receiving objects:  69% (473331/685986), 497.31 MiB | 43.85 MiB/s   
Receiving objects:  70% (480191/685986), 519.46 MiB | 43.86 MiB/s   
Receiving objects:  70% (483841/685986), 519.46 MiB | 43.86 MiB/s   
Receiving objects:  71% (487051/685986), 541.49 MiB | 43.85 MiB/s   
Receiving objects:  72% (493910/685986), 563.70 MiB | 44.10 MiB/s   
Receiving objects:  72% (494910/685986), 563.70 MiB | 44.10 MiB/s   
Receiving objects:  73% (500770/685986), 576.19 MiB | 41.96 MiB/s   
Receiving objects:  74% (507630/685986), 598.25 MiB | 41.96 MiB/s   
Receiving objects:  74% (511481/685986), 598.25 MiB | 41.96 MiB/s   
Receiving objects:  75% (514490/685986), 620.28 MiB | 41.96 MiB/s   
Receiving objects:  76% (521350/685986), 642.33 MiB | 41.99 MiB/s   
Receiving objects:  77% (528210/685986), 642.33 MiB | 41.99 MiB/s   
Receiving objects:  77% (534880/685986), 642.33 MiB | 41.99 MiB/s   
Receiving objects:  78% (535070/685986), 664.34 MiB | 42.00 MiB/s   
Receiving objects:  79% (541929/685986), 664.34 MiB | 42.00 MiB/s   
Receiving objects:  80% (548789/685986), 686.44 MiB | 42.04 MiB/s   
Receiving objects:  80% (553863/685986), 686.44 MiB | 42.04 MiB/s   
Receiving objects:  81% (555649/685986), 708.50 MiB | 42.02 MiB/s   
Receiving objects:  82% (562509/685986), 708.50 MiB | 42.02 MiB/s   
Receiving objects:  83% (569369/685986), 730.53 MiB | 42.02 MiB/s   
Receiving objects:  83% (575573/685986), 730.53 MiB | 42.02 MiB/s   
Receiving objects:  84% (576229/685986), 752.58 MiB | 41.98 MiB/s   
Receiving objects:  85% (583089/685986), 752.58 MiB | 41.98 MiB/s   
Receiving objects:  86% (589948/685986), 774.57 MiB | 44.09 MiB/s   
Receiving objects:  87% (596808/685986), 774.57 MiB | 44.09 MiB/s   
Receiving objects:  87% (598841/685986), 774.57 MiB | 44.09 MiB/s   
Receiving objects:  88% (603668/685986), 796.73 MiB | 44.12 MiB/s   
Receiving objects:  89% (610528/685986), 796.73 MiB | 44.12 MiB/s   
Receiving objects:  90% (617388/685986), 796.73 MiB | 44.12 MiB/s   
Receiving objects:  91% (624248/685986), 796.73 MiB | 44.12 MiB/s   
Receiving objects:  92% (631108/685986), 818.87 MiB | 44.13 MiB/s   
Receiving objects:  93% (637967/685986), 818.87 MiB | 44.13 MiB/s   
Receiving objects:  94% (644827/685986), 818.87 MiB | 44.13 MiB/s   
Receiving objects:  95% (651687/685986), 818.87 MiB | 44.13 MiB/s   
Receiving objects:  96% (658547/685986), 818.87 MiB | 44.13 MiB/s   
Receiving objects:  96% (663478/685986), 818.87 MiB | 44.13 MiB/s   
Receiving objects:  97% (665407/685986), 841.00 MiB | 44.15 MiB/s   
Receiving objects:  98% (672267/685986), 841.00 MiB | 44.15 MiB/s   
Receiving objects:  99% (679127/685986), 841.00 MiB | 44.15 MiB/s   
remote: Total 685986 (delta 546954), reused 685939 (delta 546954)        
Receiving objects: 100% (685986/685986), 841.00 MiB | 44.15 MiB/s   
Receiving objects: 100% (685986/685986), 849.64 MiB | 42.05 MiB/s, done.
Resolving deltas:   0% (0/546954)   
Resolving deltas:   1% (5475/546954)   
Resolving deltas:   2% (10960/546954)   
Resolving deltas:   3% (16411/546954)   
Resolving deltas:   4% (21880/546954)   
Resolving deltas:   5% (27350/546954)   
Resolving deltas:   6% (32818/546954)   
Resolving deltas:   7% (38297/546954)   
Resolving deltas:   8% (43759/546954)   
Resolving deltas:   9% (49233/546954)   
Resolving deltas:  10% (54698/546954)   
Resolving deltas:  11% (60187/546954)   
Resolving deltas:  12% (65643/546954)   
Resolving deltas:  13% (71112/546954)   
Resolving deltas:  14% (76575/546954)   
Resolving deltas:  14% (76801/546954)   
Resolving deltas:  15% (82088/546954)   
Resolving deltas:  16% (87520/546954)   
Resolving deltas:  17% (93043/546954)   
Resolving deltas:  18% (98490/546954)   
Resolving deltas:  19% (103923/546954)   
Resolving deltas:  20% (109393/546954)   
Resolving deltas:  21% (114890/546954)   
Resolving deltas:  22% (120346/546954)   
Resolving deltas:  23% (125800/546954)   
Resolving deltas:  24% (131270/546954)   
Resolving deltas:  25% (136743/546954)   
Resolving deltas:  26% (142217/546954)   
Resolving deltas:  27% (147681/546954)   
Resolving deltas:  28% (153154/546954)   
Resolving deltas:  29% (158625/546954)   
Resolving deltas:  29% (160291/546954)   
Resolving deltas:  30% (164094/546954)   
Resolving deltas:  31% (169557/546954)   
Resolving deltas:  32% (175055/546954)   
Resolving deltas:  33% (180609/546954)   
Resolving deltas:  34% (185978/546954)   
Resolving deltas:  35% (191860/546954)   
Resolving deltas:  36% (197428/546954)   
Resolving deltas:  37% (202392/546954)   
Resolving deltas:  38% (207952/546954)   
Resolving deltas:  39% (213332/546954)   
Resolving deltas:  40% (219043/546954)   
Resolving deltas:  41% (225637/546954)   
Resolving deltas:  42% (230367/546954)   
Resolving deltas:  43% (235800/546954)   
Resolving deltas:  44% (240773/546954)   
Resolving deltas:  45% (246274/546954)   
Resolving deltas:  46% (251666/546954)   
Resolving deltas:  47% (257207/546954)   
Resolving deltas:  48% (262541/546954)   
Resolving deltas:  49% (268450/546954)   
Resolving deltas:  50% (273673/546954)   
Resolving deltas:  50% (275549/546954)   
Resolving deltas:  51% (279236/546954)   
Resolving deltas:  52% (284421/546954)   
Resolving deltas:  53% (290057/546954)   
Resolving deltas:  54% (295936/546954)   
Resolving deltas:  55% (301089/546954)   
Resolving deltas:  56% (306313/546954)   
Resolving deltas:  57% (312221/546954)   
Resolving deltas:  57% (313980/546954)   
Resolving deltas:  58% (317307/546954)   
Resolving deltas:  59% (322856/546954)   
Resolving deltas:  60% (328175/546954)   
Resolving deltas:  61% (333660/546954)   
Resolving deltas:  62% (339209/546954)   
Resolving deltas:  62% (342238/546954)   
Resolving deltas:  63% (344585/546954)   
Resolving deltas:  64% (350051/546954)   
Resolving deltas:  64% (354353/546954)   
Resolving deltas:  65% (355525/546954)   
Resolving deltas:  66% (360993/546954)   
Resolving deltas:  67% (366462/546954)   
Resolving deltas:  67% (371704/546954)   
Resolving deltas:  68% (371944/546954)   
Resolving deltas:  69% (377399/546954)   
Resolving deltas:  70% (382868/546954)   
Resolving deltas:  70% (386141/546954)   
Resolving deltas:  71% (388346/546954)   
Resolving deltas:  72% (393807/546954)   
Resolving deltas:  73% (399283/546954)   
Resolving deltas:  73% (402890/546954)   
Resolving deltas:  74% (404817/546954)   
Resolving deltas:  75% (410235/546954)   
Resolving deltas:  76% (415704/546954)   
Resolving deltas:  76% (416288/546954)   
Resolving deltas:  77% (421176/546954)   
Resolving deltas:  78% (426630/546954)   
Resolving deltas:  78% (431411/546954)   
Resolving deltas:  79% (432110/546954)   
Resolving deltas:  80% (437991/546954)   
Resolving deltas:  81% (443039/546954)   
Resolving deltas:  82% (448510/546954)   
Resolving deltas:  82% (451872/546954)   
Resolving deltas:  83% (453988/546954)   
Resolving deltas:  84% (460665/546954)   
Resolving deltas:  85% (464911/546954)   
Resolving deltas:  85% (469009/546954)   
Resolving deltas:  86% (470475/546954)   
Resolving deltas:  87% (475986/546954)   
Resolving deltas:  88% (481329/546954)   
Resolving deltas:  88% (484016/546954)   
Resolving deltas:  89% (486818/546954)   
Resolving deltas:  90% (492261/546954)   
Resolving deltas:  91% (497729/546954)   
Resolving deltas:  92% (503736/546954)   
Resolving deltas:  92% (506317/546954)   
Resolving deltas:  93% (508669/546954)   
Resolving deltas:  94% (514893/546954)   
Resolving deltas:  95% (519618/546954)   
Resolving deltas:  95% (520841/546954)   
Resolving deltas:  96% (525076/546954)   
Resolving deltas:  97% (530747/546954)   
Resolving deltas:  98% (536404/546954)   
Resolving deltas:  99% (541518/546954)   
Resolving deltas:  99% (544242/546954)   
Resolving deltas: 100% (546954/546954)   
Resolving deltas: 100% (546954/546954), done.
[0:01:00] Still working on:
[0:01:00]   v8
[0:01:06] Still working on:
[0:01:06]   v8
________ running '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor'
________ running '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in '/Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor'
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' in '/Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor'
Error: Command 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' returned non-zero exit status 1 in /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor
Failed to fetch file gs://chromium-clang-format/025ca7c75f37ef4a40f3a67d81ddd11d7d0cdb9b for v8/buildtools/mac/clang-format. [Err: /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
]
0> Failed to fetch file gs://chromium-clang-format/025ca7c75f37ef4a40f3a67d81ddd11d7d0cdb9b for v8/buildtools/mac/clang-format, skipping. [Err: /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/vendor/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
]
Downloading 1 files took 2.368308 second(s)
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Subprocess failed with return code 2.
/Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/ext/libv8/builder.rb:82:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/ext/libv8/builder.rb:80:in `chdir'
	from /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/ext/libv8/builder.rb:80:in `setup_build_deps!'
	from /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/ext/libv8/builder.rb:39:in `build_libv8!'
	from /Users/manue/tmp/vendor/gems/libv8-7.3.492.27.3beta1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1
```

**Comment by Fudoshiki** [comment]
macOS Beta 10.15 (19A501i)
homebrew
ruby-2.6 via rvm
bundle install freezes on libv8 gem

**Comment by ignisf** [comment]
it probably doesn't freeze.. just takes 40 minutes to compile since I haven't gotten around to publishing a binary version

**Comment by Fudoshiki** [comment]
@ignisf thank you

**Comment by Fudoshiki** [comment]
```zsh
Fetching libv8 7.3.492.27.1
Installing libv8 7.3.492.27.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/ext/libv8
/Users/sharevari/.rvm/rubies/ruby-2.6.3/bin/ruby -I /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0 -r ./siteconf20190715-77504-e9hbn0.rb extconf.rb
creating Makefile
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git
/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor/_gclient_v8_TNyW_2' in '/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor'
Cloning into '/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor/_gclient_v8_TNyW_2'...
remote: Sending approximately 853.36 MiB ...        
remote: Counting objects: 7685, done        
remote: Finding sources:  16% (4/25)           
remote: Finding sources:  36% (9/25)           
remote: Finding sources:  52% (13/25)           
remote: Finding sources:  72% (17/25)           
remote: Finding sources:  88% (22/25)           
remote: Finding sources: 100% (25/25)           
Receiving objects:   4% (27527/688152), 9.04 MiB | 18.08 MiB/s
Receiving objects:   7% (45929/688152), 9.04 MiB | 18.08 MiB/s
Receiving objects:  10% (68816/688152), 21.10 MiB | 21.10 MiB/s
Receiving objects:  12% (88702/688152), 34.03 MiB | 22.68 MiB/s
Receiving objects:  16% (103223/688152), 41.80 MiB | 20.90 MiB/s
Receiving objects:  19% (130749/688152), 60.77 MiB | 24.31 MiB/s
Receiving objects:  21% (149612/688152), 60.77 MiB | 24.31 MiB/s
Receiving objects:  24% (165157/688152), 82.69 MiB | 27.56 MiB/s
Receiving objects:  28% (185802/688152), 82.69 MiB | 27.56 MiB/s
Receiving objects:  31% (213328/688152), 102.28 MiB | 29.22 MiB/s
Receiving objects:  33% (231520/688152), 102.28 MiB | 29.22 MiB/s
Receiving objects:  36% (247735/688152), 121.19 MiB | 30.30 MiB/s
Receiving objects:  40% (268380/688152), 121.19 MiB | 30.30 MiB/s
Receiving objects:  43% (295906/688152), 121.19 MiB | 30.30 MiB/s
Receiving objects:  46% (316550/688152), 142.14 MiB | 31.59 MiB/s
Receiving objects:  49% (337195/688152), 142.14 MiB | 31.59 MiB/s
Receiving objects:  53% (357840/688152), 142.14 MiB | 31.59 MiB/s
Receiving objects:  55% (378484/688152), 159.60 MiB | 33.46 MiB/s
Receiving objects:  57% (392247/688152), 192.64 MiB | 35.25 MiB/s
Receiving objects:  59% (406010/688152), 230.33 MiB | 37.68 MiB/s
Receiving objects:  61% (419773/688152), 263.63 MiB | 35.86 MiB/s
Receiving objects:  63% (433536/688152), 314.41 MiB | 34.42 MiB/s
Receiving objects:  65% (447299/688152), 382.31 MiB | 33.79 MiB/s
Receiving objects:  66% (458209/688152), 419.37 MiB | 32.94 MiB/s
Receiving objects:  68% (468068/688152), 457.12 MiB | 33.88 MiB/s
Receiving objects:  70% (481707/688152), 519.21 MiB | 32.91 MiB/s
Receiving objects:  72% (495470/688152), 570.16 MiB | 33.51 MiB/s
Receiving objects:  74% (509233/688152), 589.49 MiB | 33.50 MiB/s
Receiving objects:  77% (522996/688152), 627.93 MiB | 34.40 MiB/s
Receiving objects:  79% (543641/688152), 663.15 MiB | 35.51 MiB/s
Receiving objects:  81% (557404/688152), 699.49 MiB | 36.67 MiB/s
Receiving objects:  83% (572120/688152), 735.64 MiB | 36.78 MiB/s
Receiving objects:  86% (588089/688152), 771.54 MiB | 36.23 MiB/s
Receiving objects:  89% (612456/688152), 789.76 MiB | 35.96 MiB/s
Receiving objects:  91% (626219/688152), 806.83 MiB | 35.72 MiB/s
Receiving objects:  94% (646863/688152), 827.12 MiB | 36.43 MiB/s
Receiving objects:  98% (667508/688152), 827.12 MiB | 36.43 MiB/s
remote: Total 688152 (delta 548539), reused 688145 (delta 548539)
Receiving objects: 100% (688152/688152), 853.24 MiB | 34.22 MiB/s, done.
Resolving deltas:   5% (22007/548539)
Resolving deltas:   9% (49369/548539)
Resolving deltas:  14% (71337/548539)
Resolving deltas:  18% (104037/548539)
Resolving deltas:  24% (126166/548539)
Resolving deltas:  28% (153594/548539)
Resolving deltas:  33% (181040/548539)
Resolving deltas:  38% (208555/548539)
Resolving deltas:  43% (235968/548539)
Resolving deltas:  48% (264409/548539)
Resolving deltas:  51% (279756/548539)
Resolving deltas:  56% (307204/548539)
Resolving deltas:  60% (329137/548539)
Resolving deltas:  63% (345623/548539)
Resolving deltas:  66% (362036/548539)
Resolving deltas:  69% (379710/548539)
Resolving deltas:  72% (398026/548539)
[0:01:00] Still working on:945/548539)
[0:01:00]   v8
Resolving deltas:  77% (422404/548539)
Resolving deltas:  81% (444572/548539)
Resolving deltas:  84% (462154/548539)
Resolving deltas:  88% (482718/548539)
[0:01:10] Still working on:203/548539)
[0:01:10]   v8
Resolving deltas:  92% (508351/548539)
Resolving deltas:  96% (526611/548539)
Resolving deltas:  99% (545827/548539)
Resolving deltas: 100% (548539/548539), done.
[0:01:20] Still working on:
[0:01:20]   v8
[0:01:30] Still working on:
[0:01:30]   v8
[0:01:38] Still working on:
[0:01:38]   v8
________ running '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/third_party/depot_tools/update_depot_tools_toggle.py --disable' in
'/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor'
________ running '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in
'/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor'
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' in
'/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor'
Error: Command 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' returned non-zero exit status 1 in
/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor
Failed to fetch file gs://chromium-clang-format/025ca7c75f37ef4a40f3a67d81ddd11d7d0cdb9b for v8/buildtools/mac/clang-format. [Err:
/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE
()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
]
0> Failed to fetch file gs://chromium-clang-format/025ca7c75f37ef4a40f3a67d81ddd11d7d0cdb9b for v8/buildtools/mac/clang-format, skipping. [Err:
/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/vendor/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE
()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
]
Downloading 1 files took 25.696109 second(s)
Hook 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' took 26.24 secs
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Subprocess failed with return code 2.
/Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:83:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in `chdir'
	from /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:81:in `setup_build_deps!'
	from /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/ext/libv8/builder.rb:40:in `build_libv8!'
	from /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/libv8-7.3.492.27.1 for inspection.
Results logged to /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/extensions/x86_64-darwin-19/2.6.0/libv8-7.3.492.27.1/gem_make.out

An error occurred while installing libv8 (7.3.492.27.1), and Bundler cannot continue.
Make sure that `gem install libv8 -v '7.3.492.27.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mini_racer was resolved to 0.2.6, which depends on
    libv8
```

**Comment by lloeki** [comment]
> it probably doesn't freeze.. just takes 40 minutes to compile since I haven't gotten around to publishing a binary version

@ignisf Were you successful in building it on darwin19? If that's the case it would be super helpful for you to release some binary darwin19 builds for a couple of versions on rubygems so that we can check early if our dependency gems (`mini_racer` and `sq_mini_racer`) work before the final release.

**Comment by Fudoshiki** [comment]
Failing too after clean install Catalina

**Comment by Fudoshiki** [comment]
same error

**Comment by nonusae** [comment]
Same issue here on Catalina - libv8 @ 6.7.288.46.1

**Comment by ignisf** [comment]
Hello,
Could you test these for me (the universal is for MacOS' native Ruby, the x86_64 is for RVM Ruby):

https://github.com/cowboyd/libv8/releases/download/v7.3.492.27.1/libv8-7.3.492.27.1-universal-darwin-19.gem
https://github.com/cowboyd/libv8/releases/download/v7.3.492.27.1/libv8-7.3.492.27.1-x86_64-darwin-19.gem

**Comment by lloeki** [comment]
@ignisf Quickly tested with mini_racer 0.2.6:

- universal on macOS-provided Ruby: OK
- x86_64 on custom built Ruby 2.6 (`ruby-install`): OK

Testing method: ran the following in IRB.

```
require 'mini_racer'
context = MiniRacer::Context.new
context.eval 'var adder = (a,b)=>a+b;'
puts context.eval 'adder(20,22)'
# => 42
```

Quick notes unrelated to libv8 itself:

- macOS provided `gem install` seems to fail to fetch any gem from rubygems (I just downloaded `mini_racer` manually in that case)
- one of my machines still has Xcode 10.2.1 from Mojave, where `mini_racer` failed to build against macOS-provided Ruby because of lack of Ruby headers, the other has Xcode beta, where `mini_racer` built without a hitch against macOS-provided Ruby.

**Comment by lloeki** [comment]
Additional note: Catalina thinned everything to `x86_64` so not sure about `universal`?

**Comment by nonusae** [comment]
Solved my problem by require `'mini_racer', '~> 0.2.6'` instead of 'mini_racer', '~> 0.2.0' to make gemfile.lock require `libv8 7..3492.271` instead of `6.7.288.46.1` and use above gem file to install `libv8`.

Thanks you.

**Comment by lloeki** [comment]
@ignisf also ran unit tests on `mini_racer`'s master. All tests pass but I have an extra `Uncaught TypeError: Cannot create property 'kevin' on number '2'` output:

```
> rake test
/Users/lloeki/Workspace/contrib/mini_racer/test/mini_racer_test.rb:734: warning: assigned but unused variable - context2
/Users/lloeki/Workspace/contrib/mini_racer/test/mini_racer_test.rb:422: warning: method redefined; discarding old test_invalid_warmup_sources_throw_an_exception
/Users/lloeki/Workspace/contrib/mini_racer/test/mini_racer_test.rb:416: warning: previous definition of test_invalid_warmup_sources_throw_an_exception was here
Run options: --seed 7522

# Running:

........SS.................................................<unknown>:65: Uncaught TypeError: Cannot create property 'kevin' on number '2'
..............

Fabulous run in 1.547824s, 47.1630 runs/s, 83.9889 assertions/s.

73 runs, 130 assertions, 0 failures, 0 errors, 2 skips
```

I don't know if this was present before.

Anyway, thanks *a lot* for this @ignisf !

**Comment by ignisf** [comment]
I've pushed the `darwin-19` binaries to rubygems

**Comment by willc0de4food** [comment]
How would one go about getting therubyracer to use that version of libv8? I was able to gem install therubyracer, but bundle still fails with `Libv8::Location::System::NotFoundError`

**Comment by ignisf** [comment]
@willc0de4food, unfortunately the only way to do so is by rewriting large parts of therubyracer. https://github.com/cowboyd/therubyracer/pull/348

**Comment by willc0de4food** [comment]
> @willc0de4food, unfortunately the only way to do so is by rewriting large parts of therubyracer. [cowboyd/therubyracer#348](https://github.com/cowboyd/therubyracer/pull/348)

Ahh, I see.. Well, at least it's in the works. Thanks!

**Comment by drewish** [comment]
Got past my roadblock. It was getting stuck in `Libv8::Builder::setup_build_deps!` with a `git-remote-https`? (I should noted the name at the time) process at 100% CPU trying to checkout the source but making no progress over several hours. 

Eventually after trying it a few times I just went into `vendor/v8` and did a `git fetch -v` so I could see what was happening. That finished in a matter of seconds and then I was able to switch back up and kick off a build.

**Comment by ahujasushant** [comment]
https://stackoverflow.com/questions/33475709/install-therubyracer-gem-on-osx-10-11-el-capitan/36263542

Try using this solution. This worked for me.

**Comment by cgriego** [comment]
@ignisf Could we get a or some some darwin19 binary gem packages that satisfy therubyracer's version constraint?

**Comment by channainfo** [comment]
> Solved my problem by require `'mini_racer', '~> 0.2.6'` instead of 'mini_racer', '~> 0.2.0' to make gemfile.lock require `libv8 7..3492.271` instead of `6.7.288.46.1` and use above gem file to install `libv8`.
> 
> Thanks you.

Work for me too.

**Comment by nightpool** [comment]
Hi all, we've published binary versions for Catalina for both the 8.4 and 7.3 releases. Users of `therubyracer` are encouraged to switch to `mini_racer`, which uses up to date versions of v8 that have been compiled for Catalina.

**Comment by LucasKuhn** [comment]
I updated 3 gems at once, worked for me: 
```bash
bundle update libv8 mini_racer mimemagic
```
